name: CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build project
      uses: webbertakken/unity-builder@v0.10
      with:
        unityVersion: 2019.4.13f1
        projectPath: unity
        targetPlatform: Android
    
    - name: Build unity
      run: |
        cd unity/Build
        ../../android/gradlew build
    
    - name: Build android
      run: |
        cd android
        ./gradlew build
