name: CI-Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build project
      uses: webbertakken/unity-builder@v0.10
      with:
        unityVersion: 2019.4.13f1
        projectPath: unity
        targetPlatform: Android
        buildsPath: unity/Build
        
    # Output
    - uses: actions/upload-artifact@v1
      with:
        name: Build
        path: unity/Build
    
#     - name: Build unity
#       run: |
#         ls -la unity/Build/Android
#         cd unity/Build/Android
#         ../../../android/gradlew build
    
    - name: Build android
      run: |
        cd android
        ./gradlew build
